sudo: required
language: node_js
node_js:
  - "8.9"
install: 
  - npm install
script:
  - npm test 
after_success:
- npm cache clean
- sh $TRAVIS_BUILD_DIR/.travis/version.sh
- sleep 5s
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: release
    tags: false